theme: jekyll-theme-minimal
title: gs-opt
description: Human-in-the-loop batched optimization with Google Sheets.

# Tell Jekyll to include the test_results directory in the site build
include:
  - "test_results"

# Tell Jekyll to process our custom stylesheet
sass:
  sass_dir: assets/css
